[KAFKA]
#Defines the list of Kafka Server URI/Nodename:port. Example: ["localhost:9092"].
KServersInfo   = [""]
# Timeout of KAFKA Server connection drop / Keepalive.
KTimeout   = 10
# TLS Configuration Data
KAFKACertFile       = ""
KAFKAKeyFile        = ""
KAFKACAFile         = ""
